language: node_js

node_js:
  - node
  - "10"

os:
  - osx
  - linux

notifications:
  email:
    on_failure: always
    on_success: never

cache:
  directories:
    - node_modules

install:
  - npm install

jobs:
  include:
    - stage: test
      script: npm run test:report
    - stage: deploy
      script: npx semantic-release
