language: node_js

node_js:
  - node

os:
  - osx
  - linux

notifications:
  email:
    on_failure: always
    on_success: never

cache:
  directories:
    - node_modules

install:
  - npm install

script: npm run test:report


jobs:
  include:
    - stage: deploy
      script: npx semantic-release
